#
# RaspberryPiイメージのビルド
#
name: build Raspberry Pi image

on: workflow_dispatch

env:
  BUILDROOT_IMAGE_TAG: enchan1207/buildroot
  BUILDROOT_IMAGE_FILE: enchan1207-buildroot

jobs:
  build_rpi_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Raspberry Pi イメージのビルド
      - uses: Enchan1207/rpi-buildroot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: buildroot.config
          pre_build_script: prebuild.sh
          post_build_script: postbuild.sh
          output_path: sdcard.img

      # リリースドラフトを作成し、ビルドしたイメージを同梱
      - name: draft release
        uses: softprops/action-gh-release@v1
        with:
          name: release draft
          draft: true
          files: sdcard.img
